# Generated by Django 4.2.30 on 2026-07-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_visitors', models.PositiveIntegerField(default=0)),
                ('new_customers', models.PositiveIntegerField(default=0)),
                ('products_sold', models.PositiveIntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name_plural': 'daily stats',
                'db_table': 'daily_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('session_key', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'page_views',
                'indexes': [models.Index(fields=['path', '-created_at'], name='page_views_path_23796e_idx')],
            },
        ),
    ]
